/*
 * EventPanel.java
 *
 * Created on 21 de Dezembro de 2008, 17:49
 */

package org.gcreator.events;

import java.awt.BorderLayout;
import org.gcreator.gui.EventActionRenderer;

/**
 *
 * @author  luis
 */
public class EventPanel extends javax.swing.JPanel {

    private static final long serialVersionUID = 1;
    
    private Event e = null;
    
    /**
     * Creates new form EventPanel
     * @param e The event that this panel should represent
     */
    public EventPanel(Event e) {
        this.e = e;
        initComponents();
        setLayout(new BorderLayout());
        render = new EventActionRenderer(e);
        render.setVisible(true);
        add(render, BorderLayout.CENTER);
        render.updateUI();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public EventActionRenderer render = null;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
