/*
 * ActorProperties.java
 *
 * Created on 27 de Dezembro de 2008, 16:30
 */

package org.gcreator.gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import org.gcreator.formats.Scene;
import org.gcreator.gui.validators.ActorValidator;

/**
 *
 * @author  luis
 */
public class ActorProperties extends javax.swing.JPanel {
    private static final long serialVersionUID = -3017742931775563622L;

    private Scene.ActorInScene a;
    private SceneEditorArea area;
    
    /** Creates new form ActorProperties
     * @param a The Actor to edit
     * @param area The area where the actor is drawn
     */
    public ActorProperties(Scene.ActorInScene a, SceneEditorArea area) {
        this.a = a;
        this.area = area;
        initComponents();
        actorChooser.setResourceValidator(new ActorValidator());
        actorChooser.setSelectedFile(a.bf);
        actorChooser.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent evt){
                ActorProperties.this.a.bf = actorChooser.getSelectedFile();
                ActorProperties.this.area.repaint();
            }
        });
        xField.setText(""+a.x);
        yField.setText(""+a.y);
        DocumentListener dl = new DocumentListener() {

            public void insertUpdate(DocumentEvent e) {
                update(e);
            }

            public void removeUpdate(DocumentEvent e) {
                update(e);
            }

            public void changedUpdate(DocumentEvent e) {
                update(e);
            }
            
            public void update(DocumentEvent e){
                try{
                    ActorProperties.this.a.x = Integer.parseInt(xField.getText());
                }
                catch(Exception ex){}
                try{
                    ActorProperties.this.a.y = Integer.parseInt(yField.getText());
                }
                catch(Exception ex){}
                ActorProperties.this.area.repaint();
            }
        };
        xField.getDocument().addDocumentListener(dl);
        yField.getDocument().addDocumentListener(dl);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        actorChooser = new org.gcreator.gui.ResourceChooser();
        jLabel2 = new javax.swing.JLabel();
        xField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        yField = new javax.swing.JTextField();

        jLabel1.setText("Actor:");

        jLabel2.setText("x");

        xField.setText("0");

        jLabel3.setText("y");

        yField.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(actorChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(yField, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                            .addComponent(xField, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(actorChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(xField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(yField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.gcreator.gui.ResourceChooser actorChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField xField;
    private javax.swing.JTextField yField;
    // End of variables declaration//GEN-END:variables

}
