/*
 * SceneProperties.java
 *
 * Created on 27 de Dezembro de 2008, 13:50
 */

package org.gcreator.gui;

import java.awt.Color;
import javax.swing.JColorChooser;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import org.gcreator.editors.SceneEditor;

/**
 *
 * @author  luis
 */
public class SceneProperties extends javax.swing.JPanel {

    private static final long serialVersionUID = 5613L;
    
    
    private SceneEditor editor;
    private Color ok;
    
    /** Creates new form SceneProperties */
    public SceneProperties(SceneEditor editor) {
        initComponents();
        this.editor = editor;
        jTextField1.setText(""+ editor.s.width);
        jTextField2.setText(""+ editor.s.height);
        ok = jTextField1.getBackground();
        validateTextFields();
        DocumentListener d = new DocumentListener(){
            public void insertUpdate(DocumentEvent evt){
                update(evt);
            }
            public void removeUpdate(DocumentEvent evt){
                update(evt);
            }
            public void changedUpdate(DocumentEvent evt){
                update(evt);
            }
            public void update(DocumentEvent evt){
                validateTextFields();
            }
        };
        jTextField1.getDocument().addDocumentListener(d);
        jTextField2.getDocument().addDocumentListener(d);
        jPanel1.setBackground(editor.s.bgColor);
    }
    
    private void validateTextFields(){
        try{
            int i = Integer.parseInt(jTextField1.getText());
            if(i<=0){
                throw new Exception();
            }
            jTextField1.setBackground(ok);
            editor.s.width = i;
        }
        catch(Exception e){
            jTextField1.setBackground(Color.RED);
        }
        
        try{
            int i = Integer.parseInt(jTextField2.getText());
            if(i<=0){
                throw new Exception();
            }
            jTextField2.setBackground(ok);
            editor.s.height = i;
        }
        catch(Exception e){
            jTextField2.setBackground(Color.RED);
        }
        editor.jScrollPane1.updateUI();
        if(editor.sea!=null){
            editor.sea.updateUI();
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        jLabel1.setText("Width:");

        jTextField1.setText("jTextField1");

        jLabel2.setText("Height:");

        jTextField2.setText("jTextField2");

        jLabel3.setText("Background Color:");

        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 212, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)))
                    .addComponent(jLabel3))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(287, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
    Color c = JColorChooser.showDialog(this, "Select color", editor.s.bgColor);
    if(c!=null){
        editor.s.bgColor = c;
        jPanel1.setBackground(editor.s.bgColor);
        editor.sea.repaint();
    }
}//GEN-LAST:event_jPanel1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

}
