/*
 * SceneProperties.java
 *
 * Created on 27 de Dezembro de 2008, 13:50
 */

package org.gcreator.gui;

import java.awt.Color;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import org.gcreator.editors.SceneEditor;

/**
 *
 * @author  luis
 */
public class SceneProperties extends javax.swing.JPanel {

    private static final long serialVersionUID = 5613L;
    
    
    private SceneEditor editor;
    private Color ok;
    
    /** Creates new form SceneProperties */
    public SceneProperties(SceneEditor editor) {
        initComponents();
        this.editor = editor;
        jTextField1.setText(""+ editor.s.width);
        jTextField2.setText(""+ editor.s.height);
        ok = jTextField1.getBackground();
        validateTextFields();
        DocumentListener d = new DocumentListener(){
            public void insertUpdate(DocumentEvent evt){
                update(evt);
            }
            public void removeUpdate(DocumentEvent evt){
                update(evt);
            }
            public void changedUpdate(DocumentEvent evt){
                update(evt);
            }
            public void update(DocumentEvent evt){
                validateTextFields();
            }
        };
        jTextField1.getDocument().addDocumentListener(d);
        jTextField2.getDocument().addDocumentListener(d);
    }
    
    private void validateTextFields(){
        try{
            int i = Integer.parseInt(jTextField1.getText());
            if(i<=0){
                throw new Exception();
            }
            jTextField1.setBackground(ok);
            editor.s.width = i;
        }
        catch(Exception e){
            jTextField1.setBackground(Color.RED);
        }
        
        try{
            int i = Integer.parseInt(jTextField2.getText());
            if(i<=0){
                throw new Exception();
            }
            jTextField2.setBackground(ok);
            editor.s.height = i;
        }
        catch(Exception e){
            jTextField2.setBackground(Color.RED);
        }
        editor.jScrollPane1.updateUI();
        if(editor.sea!=null){
            editor.sea.updateUI();
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();

        jLabel1.setText("Width:");

        jTextField1.setText("jTextField1");

        jLabel2.setText("Height:");

        jTextField2.setText("jTextField2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(365, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

}
