/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainFrame.java
 *
 * Created on 30/Out/2009, 23:36:13
 */
package org.gcreator.pineapple.pinec;

import java.io.BufferedReader;
import java.io.Reader;
import java.io.StringReader;
import java.util.List;
import org.gcreator.pineapple.pinec.lexer.Lexer;
import org.gcreator.pineapple.pinec.lexer.LexerHandler;
import org.gcreator.pineapple.pinec.parser.Parser;
import org.gcreator.pineapple.pinec.parser.tree.ClassConstant;
import org.gcreator.pineapple.pinec.parser.tree.Document;

/**
 *
 * @author luis
 */
public class MainFrame extends javax.swing.JFrame {

    /** Creates new form MainFrame */
    public MainFrame() {
        initComponents();
        setSize(500, 500);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane2 = new javax.swing.JEditorPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        jButton1.setText("Run");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.NORTH);

        jSplitPane1.setDividerLocation(250);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jEditorPane1.setBackground(java.awt.Color.white);
        jEditorPane1.setFont(new java.awt.Font("Courier New", 0, 14));
        jEditorPane1.setForeground(java.awt.Color.black);
        jScrollPane1.setViewportView(jEditorPane1);

        jSplitPane1.setTopComponent(jScrollPane1);

        jEditorPane2.setEditable(false);
        jScrollPane2.setViewportView(jEditorPane2);

        jSplitPane1.setRightComponent(jScrollPane2);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        final String content = jEditorPane1.getText();

        final LexerHandler handler = new LexerHandler();
        final Reader strReader = new StringReader(content);
        final Reader reader = new BufferedReader(strReader);

        try {
            final Lexer lexer = new Lexer(reader, handler);
            lexer.run();
            final Parser parser = new Parser(handler);
            final Document d = parser.run();

            final StringBuilder str = new StringBuilder();

            final List<CompilerError> errors = handler.errors;
            boolean worked = true;

            if (!errors.isEmpty()) {
                str.append("At <untitled>:\n");
            }
            for (final CompilerError error : errors) {
                if(error.isFatal()){
                    worked = false;
                }
                str.append("\t" + error.toString()+"\n");
            }

            if(worked){
                str.append("/***How the compiler sees it***/\n\n");
                for (final ClassConstant cls : d.classes) {
                    if (cls.behaviorFlag) {
                        str.append("magic ");
                    }
                    str.append(cls.toString() + "\n");
                }
            }
            jEditorPane2.setText(str.toString());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void amain(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JEditorPane jEditorPane2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
