/*
 * EventPanel.java
 *
 * Created on 21 de Dezembro de 2008, 17:49
 */
package org.gcreator.pineapple.events;

import java.awt.BorderLayout;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import org.fife.ui.rsyntaxtextarea.RSyntaxTextArea;
import org.fife.ui.rtextarea.RTextScrollPane;


/**
 * Event Editor.
 * 
 * @author Luís Reis
 */
public class EventPanel extends javax.swing.JPanel{

    private static final long serialVersionUID = 1;
    private Event e = null;
    private RSyntaxTextArea textArea;
    
    public Event getEvent(){
        return e;
    }

    /**
     * Creates new form EventPanel
     * 
     * @param e The event that this panel should represent
     */
    public EventPanel(Event e) {
        this.e = e;
        initComponents();
        textArea = new RSyntaxTextArea();
        textArea.restoreDefaultSyntaxHighlightingColorScheme();
        textArea.setAutoIndentEnabled(true);
        textArea.setBracketMatchingEnabled(true);
        textArea.setSyntaxEditingStyle(RSyntaxTextArea.PINEDL_SYNTAX_STYLE);
        RTextScrollPane scroll = new RTextScrollPane(getWidth(), getHeight(), textArea, true);
        scroll.setVisible(true);
        textArea.setVisible(true);
        textArea.setText(e.getPineDL());
        textArea.getDocument().addDocumentListener(new DocumentListener(){
            public void changedUpdate(DocumentEvent evt){
                update(evt);
            }
            public void insertUpdate(DocumentEvent evt){
                update(evt);
            }
            public void removeUpdate(DocumentEvent evt){
                update(evt);
            }
            public void update(DocumentEvent evt){
                EventPanel.this.e.setPineDL(textArea.getText());
            }
        });
        add(scroll, BorderLayout.CENTER);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
