/*
 * SceneEditor.java
 *
 * Created on 21 de Dezembro de 2008, 20:19
 */
package org.gcreator.editors;

import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;
import org.gcreator.actions.ActionType;
import org.gcreator.dnd.PaletteAction;
import org.gcreator.formats.Scene;
import org.gcreator.game2d.PaletteUser;
import org.gcreator.gui.BehaviorPanel;
import org.gcreator.gui.DocumentPane;
import org.gcreator.gui.ResourceChooser;
import org.gcreator.gui.SceneEditorArea;
import org.gcreator.gui.SceneProperties;
import org.gcreator.gui.validators.ActorValidator;
import org.gcreator.project.io.BasicFile;
import org.noos.xing.mydoggy.ToolWindow;

/**
 * The editor of game scenes
 * @author Luís Reis
 */
public class SceneEditor extends DocumentPane implements PaletteUser {

    private static final long serialVersionUID = 1L;
    public Scene s = null;
    private BehaviorPanel panel = null;
    private JPanel palette = null;
    public ResourceChooser actorChooser = new ResourceChooser();
    public SceneProperties sp = null;
    public SceneEditorArea sea = null;

    /** Creates new form SceneEditor */
    public SceneEditor(BasicFile f) {
        super(f);
        palette = new JPanel();
        initComponents();
        s = new Scene();
        setModified(true);
        panel = new BehaviorPanel(s, this);
        panel.setVisible(true);
        jTabbedPane1.add(panel, "Behavior");
        palette.setVisible(true);
        palette.setLayout(new GridLayout(0, 1));
        updatePaletteContent();
        actorChooser.setResourceValidator(new ActorValidator());
        actorChooser.setVisible(true);
        sp = new SceneProperties(this);
        jPanel1.add(sp, BorderLayout.CENTER);
        sea = new SceneEditorArea();
        sea.setVisible(true);
        sea.sceneEditor = this;
        sea.updateUI();
        jScrollPane1.setViewportView(sea);
    }

    public void updatePaletteContent() {
        palette.removeAll();
        if (jTabbedPane1.getSelectedComponent() == panel) {
            JLabel l = new JLabel("<html><b>Actions:</b></html>");
            l.setVisible(true);
            palette.add(l);

            for (ActionType type : ActionType.actionTypes) {
                PaletteAction act = new PaletteAction(type);
                palette.add(act);
                act.setVisible(true);
            }
        }
        else{
            palette.add(actorChooser);
        }
    }

    public boolean doPalette(ToolWindow window, JPanel panel) {
        panel.removeAll();
        panel.setLayout(new FlowLayout());
        panel.add(palette);
        return true;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();

        setLayout(new java.awt.BorderLayout());

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jPanel1.setLayout(new java.awt.BorderLayout());
        jSplitPane1.setLeftComponent(jPanel1);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jButton1.setText("Add");
        jButton1.setSelected(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);

        jButton2.setText("Edit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_START);
        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jSplitPane1.setRightComponent(jPanel2);

        jTabbedPane1.addTab("Environment", jSplitPane1);

        add(jTabbedPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
    updatePaletteContent();
}//GEN-LAST:event_jTabbedPane1StateChanged

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    jButton1.setSelected(true);
    jButton2.setSelected(false);
    sea.mode = SceneEditorArea.MODE_ADD;
    sea.repaint();
}//GEN-LAST:event_jButton1ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    jButton1.setSelected(false);
    jButton2.setSelected(true);
    sea.mode = SceneEditorArea.MODE_EDIT;
    sea.repaint();
}//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
