#pragma once

#ifndef __PINEC_LEXER_KEYWORDS_H__
#define __PINEC_LEXER_KEYWORDS_H__

#define KT_ARRAY		(0)
#define KT_BOOL			(1)
#define KT_BREAK		(2)
#define KT_CALLEE		(3)
#define KT_CASE			(4)
#define KT_CHAR			(5)
#define KT_CLASS		(6)
#define KT_CONST		(7)
#define KT_CONTINUE		(8)
#define KT_DEFAULT		(9)
#define KT_DO			(10)
#define KT_ELSE			(11)
#define KT_EXTENDS		(12)
#define KT_FALSE		(13)
#define KT_FINAL		(14)
#define KT_FOR			(15)
#define KT_FUNCTION		(16)
#define KT_IF			(17)
#define KT_IS			(18)
#define KT_NEW			(19)
#define KT_NULL			(20)
#define KT_NUMBER		(21)
#define KT_PRIVATE		(22)
#define KT_PROTECTED	(23)
#define KT_PUBLIC		(24)
#define KT_RANGE		(25)
#define KT_REFERENCED	(26)
#define KT_RETURN		(27)
#define KT_STATIC		(28)
#define KT_STRING		(29)
#define KT_SUPER		(30)
#define KT_SWITCH		(31)
#define KT_THIS			(32)
#define KT_TRUE			(33)
#define KT_TYPE			(34)
#define KT_VAR			(35)
#define KT_VIRTUAL		(36)
#define KT_WHILE		(37)

#endif
